import type { Metadata } from "next";
import "./globals.css";
import { PlaylistProvider } from "./utilities/PlaylistContext";
import { UserProvider } from "./utilities/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=''>
        <UserProvider>
          <PlaylistProvider>
              {children}

          </PlaylistProvider>
        </UserProvider>
      </body>
    </html>
  );
}
